import Head from "next/head";
import Image from "next/image";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import { Gallery } from "../styles/Gallery";
import Products from "../components/Products";

export default function Home() {
  //FETCH PRODUCT_QUERY INTO
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //check for data coming from the server
  if (fetching) return <p>Loading ....</p>;
  if (error) return <p>Oh no ... {error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="items-center">
          <h1>Cake Shop</h1>
        </div>
        <Gallery>
          {products.map((product, i) => (
            <Products key={i} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
